### ISSUE TITLE
6.1.0 version misplaces CHANGELOG.md

### ISSUE THREAD

**Issue by dvdesolve** [scrooloose/nerdtree#1044]
- [x] I have searched the [issues](https://github.com/scrooloose/nerdtree/issues) for an answer to my question.
- [x] I have reviewed the NERDTree documentation. `:h NERDTree`
- [x] I have reviewed the [Wiki](https://github.com/scrooloose/nerdtree/wiki).
- [x] I have searched the web for an answer to my question.

#### Environment (for bug reports)
- [x] Operating System: Arch Linux rolling
- [x] Vim/Neovim version: 8.1.2102
- [x] NERDTree version, found on 1st line in NERDTree quickhelp `?`: 6.1.0
- [x] vimrc settings
```
"" load and set extra plugins
let &runtimepath.=','.$PLUMED_VIMPATH

let g:ycm_extra_conf_globlist = ['~/radiotechnics/*']
let g:ycm_use_clangd = 0
let g:ycm_clangd_binary_path = '/usr/bin/clangd'

autocmd vimenter * NERDTree
autocmd vimenter * wincmd p
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
"autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

"" disable vi compatibility
set nocompatible

"" save backups
set backup

"" enable modelines
set modeline
set modelines=5

"" interface
set number
set laststatus=2
set statusline=%#DiffAdd#%F%h%m%r%=%#DiffChange#[%Y\ \|\ %{&fenc}/%{&ff}]\ [%l/%L,%v]\ [%p%%]%*
set showmode
set showcmd

"" fast scrolling
set ttyfast

"" search settings
set hlsearch
set incsearch
set ignorecase
set smartcase

"" tabulation
set expandtab
set tabstop=4
set shiftwidth=4
set smarttab

"" indentation
filetype plugin indent on
set autoindent
set smartindent

"" paste toggle mode
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>

"" coloring
set termguicolors
let g:gruvbox_italic=1
colorscheme gruvbox
set background=dark

"" syntax highlighting
syntax on

"" wrapping
set wrap
set linebreak

"" don't store global options in sessions
set ssop-=options

"" menu staff
set wildmenu
set wcm=<TAB>

"" line endings menu
menu Endings.DOS :e++ff=dos<CR>
menu Endings.UNIX :e++ff=unix<CR>
menu Endings.MAC :e++ff=mac<CR>
imap <F7> <ESC>:emenu Endings.<TAB>
nmap <F7> :emenu Endings.<TAB>

"" encoding menu
menu Encoding.UTF-8 :e++enc=utf8<CR>
menu Encoding.KOI8-R :e++enc=koi8-r<CR>
menu Encoding.CP1251 :e++enc=cp1251<CR>
menu Encoding.CP866 :e++enc=cp866<CR>
imap <F8> <ESC>:emenu Encoding.<TAB>
nmap <F8> :emenu Encoding.<TAB>

"" build menu
menu Build.all :make<CR>
menu Build.isp :make isp<CR>
menu Build.clean :make clean<CR>
menu Build.install :make install<CR>
menu Build.uninstall :make uninstall<CR>
imap <F9> <ESC>:emenu Build.<TAB>
nmap <F9> :emenu Build.<TAB>

"" save key
imap <F2> <ESC>:w<CR><INSERT>
vmap <F2> <ESC>:w<CR><INSERT>
nmap <F2> :w<CR>
```
- [x] I've verified the issue occurs with only NERDTree installed.

#### Steps to Reproduce the Issue
1. Start `vim` and open NERDTree (I use `.vimrc` method). Change to NERDTree split (`Ctrl+W`, `Ctrl+Left`). Enter `?` and press `Enter`

#### Current Result (Include screenshots where appropriate.)
You get the following error:
```
Error detected while processing function nerdtree#ui_glue#invokeKeyMap[1]..78[50]..77[5]..<SNR>29_displayHelp[2]..235[1]
..256[12]..237[2]..nerdtree#version:
line    1:
E484: Can't open file /usr/share/vim/vimfiles/CHANGELOG.md
line    5:
E684: list index out of range: 0
Press ENTER or type command to continue
```
#### Expected Result
NERDTree help opens as usual.

Seems like `CHANGELOG.md` is installed in wrong place:
```
$ pacman -Ql vim-nerdtree | grep CHANGELOG.md
vim-nerdtree /usr/share/doc/vim-nerdtree/CHANGELOG.md
```
while NERDTree expects it be in `/usr/share/vim/vimfiles/CHANGELOG.md`

**Comment by dvdesolve** [comment]
Also reported to the [Arch Linux bugtracker](https://bugs.archlinux.org/task/63968). Maintainer of the package has implemented temporary workaround

**Comment by PhilRunninger** [comment]
The problem is that the package you're trying to install - https://www.archlinux.org/packages/community/any/vim-nerdtree/ - is not keeping the files where they need to be. My guess is that this method of installing vim plugins mixes files from all plugins together instead of using vim 8's package manager or other 3rd party plugin managers. 

This is really not a good approach, because many of these plugins contains files like `README.md` or maybe even `utils.vim` Without a plugin manager, these files can be overwritten by another plugin's files. Your ArchLinux package tries to solve that by putting what it thinks are inessential file in `/usr/share/doc/vim-nerdtree`, but that obviously doesn't work because `CHANGELOG.md` needs to be in a specific location.

I'll put a try-catch block in the `nerdtree#version()` function, but the ArchLinux admins should really switch to the native package manager in Vim 8. It really simplifies things, and prevents this sort of problem from happening by keeping the plugins intact.
