### ISSUE TITLE
Make bookmarks remember state of tree

### ISSUE THREAD

**Issue by qstrahl** [scrooloose/nerdtree#248]
I often do `:NERDTree <bookmark>` then manually open the various subdirectories I want. It would be super convenient if NERDTree remembered the open/closed state of the tree when I create a bookmark so I don't have to do it myself.

**Comment by Yavor-Ivanov** [comment]
+1

**Comment by jubalh** [comment]
+1

**Comment by gustavklopp** [comment]
+1

**Comment by protist** [comment]
+1

**Comment by hemantmits** [comment]
+1
sad so see this must have feature is pending from almost two year :(.

**Comment by alexandnpu** [comment]
+1

**Comment by igormoreno** [comment]
+1

**Comment by kelly-apollo** [comment]
+1

**Comment by scrooloose** [comment]
Gentlemen, I hear you and will be implementing this shortly.

**Comment by hshhhhh** [comment]
You all can use this plugin: https://github.com/jistr/vim-nerdtree-tabs
It works, but also "blinks" on my configuration, but you should try to use it!

**Comment by JohnTortugo** [comment]
+1

**Comment by brodieG** [comment]
+1

**Comment by scrooloose** [comment]
Hey all, I have been looking into this and have taken a stab at it here: https://gist.github.com/scrooloose/741b04b0a6dc8c69d043

Things to note:

1. I have called the idea "projects" instead of "bookmarks" since that is the direction they are heading in.

2. The concept is implemented as a nerdtree plugin at the moment. When the code/functionality stabilizes I will either add it to the core, or leave it as a plugin and hand it off to someone.

3. The interface is just `:commands` at the moment, but this may get more snazzy later according to feedback.

4. Currently, the only functionality that projects offer over bookmarks is remembering the state of the tree. I have other ideas and feature requests that may be implemented though.

Thoughts/feedback welcome.

**Comment by hshhhhh** [comment]
For the first take my love <3
For the second it produces erros.

1. When I try to ":NERDTreeProjectSave test" it says to me
```vim
Error detected while processing function 243..244..250:
line    1:
E484: Can't open file /home/hshhhhh/.NERDTreeProjects
E684: list index out of range: 0
E15: Invalid expression: "let projHashes = " . readfile(s:Project.ProjectFileName())[0]
Error detected while processing function 243:
line    1:
E714: List required
Press ENTER or type command to continue
```

2. After adding a '/home/hshhhhh/.NERDTreeProjects' file it produce an another error:

```vim
Error detected while processing function 243..246..253:
line    3:
E716: Key not present in Dictionary: getDirChildren()
E15: Invalid expression: a:rootNode.getDirChildren()
Press ENTER or type command to continue
```

**Comment by scrooloose** [comment]
Do you have the latest version of nerdtree? (I should have mentioned that)

**Comment by hshhhhh** [comment]
> Do you have the latest version of nerdtree? (I should have mentioned that)

Sorry, I've just updated and it only requires to manually create the "touch ~/.NERDTreeProjects"

**Comment by hshhhhh** [comment]
I can offer this use case (I will add it by myself, but not now). It will give you dynamical synchronization between tabs (I hope):

1) Add to .vimrc
```vim
autocmd BufNewFile,BufRead /home/user/projects/project1/* let project_name=project1
```

2) Add to NERDTree this functionality:

on_NERDTree_open or on_[tab/buffer/NERDTree]_focus_in:
```
if (project_name) then NERDTreeProjectLoad project_name
```


on_NERDTree_close or on_[tab/buffer/NERDTree]_focus_out: 
```vim
if (project_name)
then NERDTreeProjectSave project_name
```

**Comment by hshhhhh** [comment]
Also now it has a bug with autocomplete of project names:

What I do:
```vim
:NERDTreeProjectLoad t<tab>
```

What I get (but it works!):
```vim
:NERDTreeProjectLoad test
test  test  test
:NERDTreeProjectLoad test
```

**Comment by scrooloose** [comment]
OK, I have fixed 2 bugs (see latest gist):

1. The bug when `.NERDTreeProjects` didnt exist

2. The naming bug you mention above. In your example above there are actually 3 test projects. Instead of updating the test project, the code was creating new project (due to the bug).

RE your idea above `on_NERDTree_close or on_[tab/buffer/NERDTree]_focus_out: <save project>`: This effectively already happens. If you use `NERDTreeProjectLoad` and then unload the nerdtree buffer (by closing vim, or :bunload etc) then the project you have loaded will be saved again.

RE automatically loading projects when you enter the root (or by some similar condition): This might be a good idea. Unfortunately I have been drinking and can't think hard enough now :D

**Comment by hshhhhh** [comment]
> This effectively already happens. If you use NERDTreeProjectLoad and then unload the nerdtree buffer (by closing vim, or :bunload etc) then the project you have loaded will be saved again.

I want to use NERDTree this way:
* open 3 tabs
* open NERDTree in _1st tab_ and open the 4th tab with `shift+t`, NERDTree close himself automatically
* go to 2nd tab, open NERDTree and want to see the same content as it was on 1st tab

But I've started use NERDTree with `:NERDTreeFind` instead of `:NERDTreeToggle` and it works okay for me.

**Comment by scrooloose** [comment]
If I understand you correctly, you can already use `NERDTreeMirror` to accomplish this. If you want one tree viewed in many tabs, this is what `NERDTreeMirror` is for. You will be viewing the same nerdtree buffer loaded in different windows.

Have I understood you correctly?

**Comment by hshhhhh** [comment]
> Have I understood you correctly?

Oh, thank you a much! It requieres to call `:NERDTreeMirror` before 1st time calling `:NERDTreeToggle` , but it  much better then nothing.

Thank you!

P.S. -- Now I realized that I posting in wrong issue topic, sorry! :(

**Comment by scrooloose** [comment]
Hey all, FYI here is the latest version of the plugin above: https://github.com/scrooloose/nerdtree-project-plugin.

Its still a WIP really - but I have been using it for a couple of weeks. Would appreciate any feedback and ideas. If all goes well, I plan to merge this into the main repo and replace bookmarks.

**Comment by alessioalex** [comment]
@scrooloose I got an error with `b:NERDTree does not exist` when trying to save a project, even though I do have the latest version of `NERDTree` installed. Does that have to do with how bundle loads up the plugins, maybe the order..? Thanks

**Comment by rococode** [comment]
Has this been added to NERDTree already? I'm not sure if I'm just missing something or if it's not quite ready yet.

**Comment by PhilRunninger** [comment]
No, its still a separate project, and no attention has been given to it in the last couple of years. It needs some feedback and probably some work before it will be included with NERDTree, especially if it's purpose is to replace bookmarks. 

@lifecrisis, tagging you for future development consideration.

**Comment by PhilRunninger** [comment]
You can install it like you do any other plugin, and it should be ready for testing. (I haven't tried this myself, so your mileage may vary.)

**Comment by rococode** [comment]
Okay, thanks for the info! I will probably give it a try. The main functionality, for me at least, is not so much the project-like functionality but simply just remembering which folder nodes have been opened - if there is a simple way to just keep track of folder states (expanded or collapsed) persisting through vim restarts that would be equally welcome to me.

**Comment by jackson-dean** [comment]
+1. I would like this too.

**Comment by MrMebelMan** [comment]
+1, yes, please :(

**Comment by carousel** [comment]
+1 me too

**Comment by wellyal** [comment]
any updates on this? Seems an old request

**Comment by PhilRunninger** [comment]
Pull Request #929 should make the `nerdtree-project-plugin` work properly again.

**Comment by PhilRunninger** [comment]
@scrooloose 's project plugin will work once again. All you need to do is update your NERDTree and install the https://github.com/scrooloose/nerdtree-project-plugin.git plugin just like you do any other Vim plugin. Then use the commands defined in it to manage your projects:

- Create a project from the current nerdtree with
    `:NERDTreeProjectSave <name>`
- Load a project with
    `:NERDTreeProjectLoad <name>`
- Load a project from the current CWD
    `:NERDTreeProjectLoadFromCWD`
- Delete a project with
    `:NERDTreeProjectRm <name>`
