### ISSUE TITLE
Errors while starting up MacVim

### ISSUE THREAD

**Issue by srushti** [scrooloose/nerdtree#253]
With the latest update (eaf19734e73dbaa5b30f10591079043b0eba0aab) I get a bunch of errors while starting up Vim. And the started up Vim doesn't have NERDTree running either.

I'm using MacVim Snapshot 64 (which uses VIM 7.3). I'm loading the plugin into the appropriate folders using my own script (so no pathogen). Let me know if you need any more information.

> Error detected while processing ~/.vim/plugin/NERD_tree.vim:
> line  156:
> E121: Undefined variable: g:NERDTreeCreator
> E15: Invalid expression: "autocmd BufWinLeave ". g:NERDTreeCreator.BufNamePrefix() ."\* call nerdtree#saveScreenState()"
> line  159:
> E121: Undefined variable: g:NERDTreeCreator
> E15: Invalid expression: "autocmd BufEnter ". g:NERDTreeCreator.BufNamePrefix() ."\* stopinsert"
> Error detected while processing function nerdtree#postSourceActions:
> line    1:
> E121: Undefined variable: g:NERDTreeBookmark
> Error detected while processing function >nerdtree#postSourceActions..nerdtree#createDefaultBindings..NERDTreeAddKeyMap:
> line    1:
> E121: Undefined variable: g:NERDTreeKeyMap
> E121: Undefined variable: g:NERDTreeKeyMap

**Comment by awwit** [comment]
Check your privileges to the files of plugins.
Some files may have unsuitable access rights in archives with plugins.

**Comment by alevis** [comment]
@huzemin Thank! :+1: I was wondering were to put that folder.

**Comment by PhilRunninger** [comment]
@huzemin That is not where you should put user-installed plugins. They belong under the ~/.vim folder, and the best way to do it is to use a plugin manager. Pathogen, Vundle, and vim-plug are all good option. To do it manually requires you to copy all the plugin's folders into the .vim/ directory, merging them with any already existing folders. The difficulties with manually installing a plugin are:

1. two plugins may use the same filename, causing one of them to not work.
1. removing a plugin becomes problematic because you have to search all the folders to find the files that need to be deleted. You could easily miss a file or delete one that should be left alone.

I'm going to close this issue because of it's age. Reopen if necessary.
