### ISSUE TITLE
Get current NERDTree root

### ISSUE THREAD

**Issue by cpreisinger** [scrooloose/nerdtree#254]
I looked around for a bit and was unable to find a way to do this. I want to be able to grab the current NERDTree root. ctrlp seems to be able to do this because it only searches files on the current root if you set NERDTree to change the working directory.

The reason I want this is so that I can make a command to pass the contents of a file in my Rails project to the kill command on Ubuntu.

There is a server.pid file that is always in RAILS_ROOT/tmp/pids/server.pid. 

I can call :!kill $(cat <Project Directory>/tmp/pids/server.pid) in vim and it does what I want.

<Project Directory> is always the root of the NERDTree in my case but I can't find a way to grab that data for passing into vim. Am I missing something or does this feature not exist?

**Comment by lifecrisis** [comment]
A standard technique to access the root of the NERDTree does not currently exist. You may use the following line to extract the path to the tab-local NERDTree's root:

```viml
let t:root = getbufvar(t:NERDTreeBufName, 'NERDTree').root.path.str()
```
The variable `t:root` will then contain a string storing the path to the root of the current tab's NERDTree. This code is very likely to remain stable.

Since there was no other problem described above, this issue is hereby closed.
