### ISSUE TITLE
Nerdtree winSize auto

### ISSUE THREAD

**Issue by tootac** [scrooloose/nerdtree#259]
When I open nerdtree it opens exactly the half size of the terminal/gvim width. 
It is standard NERDTree without any changes. (I have couple of mappings to open it). As far  as I remember it wasn't like this before. Is there any way to change it?

**Comment by willwright82** [comment]
+1 After updating to VIM 8

**Comment by redbrain17** [comment]
Same issue with Version 7.4.52

**Comment by lifecrisis** [comment]
Someone just posted this on the Vim users mailing list.  Can anyone here give a specific set of steps to follow so that I can replicate this bug.  I've never seen the NERDTree behave in this way.

**Comment by genotrance** [comment]
I have steps to reproduce this - I just loaded the [minibufexpl](https://github.com/fholgado/minibufexpl.vim/) plugin and since then, nerdtree shows this issue.

```
let g:miniBufExplAutoStart = 1
let g:miniBufExplVSplit = 20
let g:miniBufExplBRSplit = 1
let g:miniBufExplBuffersNeeded = 0
```

iThis shows my buffers in a vertical split on the right. If I now open nerdtree, it takes up half the window. If minibufexpl doesn't load first (don't autostart and unset buffers needed) and you open nerdtree first and then minibufexpl, then nerdtree works correctly.

Also, once nerdtree is at half width and I pull it back to the right size, all toggles after that show the right width.

Hope this helps root cause this issue.

**Comment by bttf** [comment]
For me, it was `winwidth` being set in my vimrc that was being applied to my NERDTree window, causing it to be larger than it should be. This only started happening recently. Ideally I would like to keep my `winwidth` setting while not having it applied to the NERDTree window.
