### ISSUE TITLE
E117: Unknown function: nerdtree#runningWindows

### ISSUE THREAD

**Issue by zhuqingcode** [scrooloose/nerdtree#293]
I got the error above when I use vim.details:
"
Error detected while processing /root/.vim/plugin/NERD_tree.vim:
line   68:
E117: Unknown function: nerdtree#runningWindows
E116: Invalid arguments for function <SNR>7_initVariable
line   94:
E117: Unknown function: nerdtree#runningWindows
E15: Invalid expression: nerdtree#runningWindows()
line  139:
E117: Unknown function: nerdtree#loadClassFiles
line  156:
E121: Undefined variable: g:NERDTreeCreator
E15: Invalid expression: "autocmd BufWinLeave ". g:NERDTreeCreator.BufNamePrefix() ."\* call nerdtree#saveScreenState()"
line  159:
E121: Undefined variable: g:NERDTreeCreator
E15: Invalid expression: "autocmd BufEnter ". g:NERDTreeCreator.BufNamePrefix() ."\* stopinsert"
line  205:
E117: Unknown function: nerdtree#postSourceActions"

**Comment by Code-Not-Cold** [comment]
I  have encountered this problem，To resolve it,you should  first install vim-pathogen and then it will be OK.
website : https://github.com/tpope/vim-pathogen
NOTE: after install pathogen,Add this to your vimrc:  execute pathogen#infect()

**Comment by oska874** [comment]
@Code-Not-Cold not works on me (ubuntu 16.04)

**Comment by LeoTao** [comment]
first install vim-pathogen
then download NERD_tree
then put your NERD_tree folder into ~/.vim/bundle

**Comment by Amitgb14** [comment]
It works on my Fedora 23 OS.
I was refer below link and then start vim,
https://github.com/tpope/vim-pathogen

**Comment by jeantimex** [comment]
Thank you @Code-Not-Cold! Works for me on my mac.

**Comment by NorrinRadd** [comment]
This is a vim plugin.  Does it REQUIRE pathogen?? Why?  There's no way to get it to work without Pathogen or something similar?

**Comment by lifecrisis** [comment]
If you want to use the NERDTree without a plugin manager, you can simply add the root directory of the NERDTree project to your `'runtimepath'` setting.

Clone the NERDTree with `git clone` and then add the line

```viml
set runtimepath+=/path/to/nerdtree/dir
```

into your `vimrc` file.  The drawback is that you must manually update every plugin that you install this way... or write your own script to do so.

It looks like this issue doesn't identify a bug or a feature request, so I'll go ahead and close now.

**Comment by NorrinRadd** [comment]
The bug is the first post.  When pathogen, or something similar, isn't present, there are tons of errors in the plugin.  

> $ vi ~/.vim/vimrc 
Error detected while processing /Users/btrussel/.vim/bundle/nerdtree/plugin/NERD_tree.vim:
line   72:
E117: Unknown function: nerdtree#runningWindows
E15: Invalid expression: !nerdtree#runningWindows()
line  107:
E117: Unknown function: nerdtree#runningWindows
E15: Invalid expression: nerdtree#runningWindows()
line  154:
E117: Unknown function: nerdtree#loadClassFiles
line  158:
E117: Unknown function: nerdtree#ui_glue#setupCommands
line  164:
E121: Undefined variable: g:NERDTreeCreator
E15: Invalid expression: "autocmd BufLeave ". g:NERDTreeCreator.BufNamePrefix() ."* if g:NERDTree.IsOpen() | call b:NERDTree.ui.saveScreenState() | endif"
line  167:
E121: Undefined variable: g:NERDTreeCreator
E15: Invalid expression: "autocmd BufEnter ". g:NERDTreeCreator.BufNamePrefix() ."* stopinsert"
line  218:
E117: Unknown function: nerdtree#postSourceActions

===============================
Error detected while processing VimEnter Auto commands for "*":
E117: Unknown function: nerdtree#checkForBrowse
Press ENTER or type command to continue

**Comment by PhilRunninger** [comment]
No, pathogen is not required at all, nor is any other plugin manager. As @lifecrisis mentioned above, manual installation can be as simple as modifying the `runtimepath` setting in your vimrc. For  example, if you clone all the plugin repos to `~/repos/vim/`, you could add lines like so to your `vimrc` file:
```
set runtimepath+=~/repos/vim/nerdtree
set runtimepath+=~/repos/vim/vim-fugitive
```
You also need to run the `:helptags ~/repos/vim/nerdtree` and `:helptags ~/repos/vim/vim-fugitive` commands to index the help documents.

Pathogen handles the `runtimepath` modification automatically, and has a function `:Helptags` that will do all plugins' documentation at once.

Managers like Vundle and vim-plug go a step further, and provide mechanisms for installing, updating, disabling, and cleaning up plugins that are no longer wanted.

So, while a plugin manager isn't needed, using one adds functionality, and depending on who you ask, can simplify the process of managing your plugins. That is the reason it isn't listed as an official requirement, but because of its popularity, instructions are provided if you want to use it.

**Comment by NorrinRadd** [comment]
Thanks so much @PhilRunninger

**Comment by PhilRunninger** [comment]
As a followup to my previous message, I actually tried to convert my setup to a manual one. It has the advantage of one fewer plugin to manage and take up space. I thought it was working correctly, but when I tried to add another plugin as a submodule, I couldn't get vim to recognize that it was there. Since it was just an experiment, I decided to not spend a lot of time debugging it, and I will be going back to my vim-plug setup.
