### ISSUE TITLE
just want to delete one buffer

### ISSUE THREAD

**Issue by hominlinx** [scrooloose/nerdtree#301]
hi:
I am using nerdtree ,and using "autocmd bufenter \* if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif", then when I using vim(many buffers) and I want to delete one buffer(using :bd), But I get close vim ,how I can do.
thanks.

**Comment by bleached** [comment]
This seems to be unrelated to the autocmd you use. I have the same problem, and commenting that out does not solve it. :bd deletes all buffers when NERDTree is open (if they are not modified of course).

**Comment by TheAifam5** [comment]
Any progress?

**Comment by PhilRunninger** [comment]
`:bd` closes the buffer in the active window. If there are multiple windows, it also closes that window. If only the NERDTree window remains, your autocmd kicks in and closes it too. Since that is the last window to be closed, vim is stopped too. This is not a NERDTree issue, but a common complaint about vim, and there are various solutions out there on the interwebs. One that I've used before is `:bn|bp #`. It goes to the next buffer, and then deletes the buffer you just came from. Since you're not deleting an active buffer, the window stays open. There are, however, edge cases where this won't work correctly. This [StackOverflow thread](https://stackoverflow.com/questions/1444322/how-can-i-close-a-buffer-without-closing-the-window) is a good summary of the issue.
