### ISSUE TITLE
Automatically highlight currently opened buffer

### ISSUE THREAD

**Issue by matjon** [scrooloose/nerdtree#369]
It would be nice if nerdtree automatically highlighted the currently active buffer.
But please ask author for relicense because the code is from Stack Exchange and so is under CC-BY-SA.

http://choorucode.com/2014/05/05/how-to-highlight-current-file-in-nerdtree/
http://superuser.com/a/474298

**Comment by lifecrisis** [comment]
A similar feature was also suggested in issue #670. It was rejected because it's an unnecessary feature that would be complex to implement.

If by "highlight", you mean simply to automatically run `:NERDTreeFind` for the active buffer, the code you included in the links can be added to your vimrc to get that functionality. It seems like it would work just fine.

Thanks, anyway, for the suggestion.
