### ISSUE TITLE
Many NerdTree errors when loading GVim

### ISSUE THREAD

**Issue by pgathogo** [scrooloose/nerdtree#372]
Hi,
Am getting a looong list of errors just after installing NerdTree on to my Vim folder, see the image for error list. I did a git clone into the ../vimfiles/plugin folder, and when i run Gvim i get the errors!
- Vim 7.4
- Windows 7, 64bit

Help!
Paul

![image](https://cloud.githubusercontent.com/assets/155431/3948315/56b7619a-26a3-11e4-94b4-1653d4918001.png)

**Comment by saltycraig** [comment]
Confirming I get similar errors on Windows 7 64-bit gVim 7.4. My nerdtree install path is: $HOME\vimfiles\plugin\nerdtree

**Comment by PhilRunninger** [comment]
@pgathogo, @saltycraig, and many others,

Your NERDTree is installed incorrectly. It is recommended that you use a plugin manager like [pathogen](https://github.com/tpope/vim-pathogen) or [Vundle](https://github.com/VundleVim/Vundle.vim). You'll see why when I describe the manual alternative.

To manually install NERDTree, you need to clone it to some temporary location, then copy the folders into your `C:\Users\<username>\vimfiles` folder. Windows will recognize that some or all of the folders already exist, and will merge the contents. So far so good, so why is this a bad idea?
1. It makes installing updates harder. Instead of simple `git pull`s or (in the case of Vundle) a `:PluginUpdate` command, you'll need to repeat the installation process over again. And this applies to all plugins you want to update.
1. It makes uninstalling plugins harder. To get rid of a plugin, you must manually go into all the folders, find the (potentially dozens of) files that belong to just that plugin, and delete them. Be careful you don't accidentally delete one for a plugin you want to keep around.
1. You run the risk of plugins using the same filename, and one overwriting the other. Now a plugin that once worked is broken.

Plugin managers keep the plugins in their separate git repositories, which gives you much greater control over updating, deleting, activating, or deactivating plugins. At some point, I will be creating a Wiki page just for Installing NERDTree, as this is a consistent problem in the Issues.

I am going to close this issue because it's over 3 years old, and you've probably figure this out already.
