### ISSUE TITLE
Copying directories should ignore vim swap files

### ISSUE THREAD

**Issue by Sjlver** [scrooloose/nerdtree#388]
When copying folders using the "m c" command while files in these folders are currently opened, NERDtree also copies the swap (`.*.swp`) files.

When I then try to open the newly-created destination file, vim complains because a `.swp` file already exists.

It would be great if NERDtree could be a bit smarter about this, and not copy `.swp` files corresponding to files that are opened in the same instance of vim. This would be consistent with the behavior for renaming or deleting files; there, NERDtree warns me about files that are currently being opened, and takes the appropriate actions.

**Comment by lifecrisis** [comment]
This issue is quite old.  I'm afraid I also disagree with adding the feature described here.  A far better solution is to use the `'directory'` setting included with Vim.  This will allow you to place your own swap files in a designated location.  Read more by running `:help 'directory'` in a Vim window.  Thanks!
