### ISSUE TITLE
Error detected after moving a file

### ISSUE THREAD

**Issue by c10b10** [scrooloose/nerdtree#435]
I always get a similiar error:

![screenshot 2015-04-20 15 02 21](https://cloud.githubusercontent.com/assets/306633/7229609/5eecdff2-e76e-11e4-9b18-81bcadba81ba.png)

after I rename a file (even when the file isn't open in any buffer). These are my NT vimrc settings:

``` vim
    augroup ps_nerdtree
        au!

        au Filetype nerdtree setlocal nolist
        " au Filetype nerdtree nnoremap <buffer> K :q<cr>
    augroup END

    let NERDTreeHighlightCursorline = 1
    let NERDTreeIgnore = ['\~$', '.git$[[dir]]', '.DS_Store', '.*\.pyc$',
                        \ 'pip-log\.txt$', 'whoosh_index', 'xapian_index', '.*.pid',
                        \ 'monitor.py', '.*-fixtures-.*.json', '.*\.o$', 'db.db',
                        \ 'tags.bak']
    let NERDTreeShowHidden = 1
    let NERDTreeMinimalUI = 1
    let NERDTreeDirArrows = 1
    let NERDChristmasTree = 1
    let NERDTreeChDirMode = 1
    let NERDTreeMapJumpFirstChild = 'gK'
    let NERDTreeBookmarksFile = expand('~/some/path')
    let NERDTreeShowLineNumbers=1
    let g:NERDTreeWinPos = "left"
    let g:NERDTreeWinSize = 35
```

Is this a bug?

**Comment by jyc** [comment]
I actually ran into this as well just today.

**Comment by PhilRunninger** [comment]
This seems to be caused by the fact that the folder specified to hold the bookmarks file is not present. In @c10b10 's screenshot, it is `/Users/c10b10/bin/dotfiles/vim/nt` that doesn't exist. I can only assume that the vimrc text was edited to be `~/some/path` after the screenshot was taken. If you create the folder first, then this error goes away, but it is a workaround, and we can consider this to be a bug.
