### ISSUE TITLE
How can I access g:NERDTree.IsOpen() after the refactor?

### ISSUE THREAD

**Issue by tony** [scrooloose/nerdtree#445]
HEY @scrooloose , did you know that you are AWESOME? :)

A code update changed some behavior for me, basically I have a function that will open NERDTree but avoid buffers like tagbars / tag list.

Here is the code:

```VimL

fu! NERDTreeFindPrevBuf()

    if nerdtree#isTreeOpen()
      execute ':NERDTreeClose'
    elseif (!filereadable(bufname('%')) || (bufname('%') == '__Tag_List__') || (bufname('%') == '__Tagbar__'))
      echo "Previous buf not valid or readable file."
      execute ':NERDTree ' . getcwd()
    else
      execute ':NERDTreeFind'
    endif
endfunction

fu! NerdTreeFindPrevBuf2()
  " For posterity, here's the old one that'd move back to the previous buffer if they
  "  were inside taglist / tagbar :)
  if (bufname('%') == '__Tag_List__') || (bufname('%') == '__Tagbar__')
    wincmd p " previous window
    if !filereadable(bufname('%'))
            wincmd h " mv one window to the left
    endif
    execute ':NERDTreeFind'
  else
    if !filereadable(bufname('%'))
      echo "Previous buf not valid or readable file."
      execute ':NERDTree ' . getcwd()
    else
      execute ':NERDTreeFind'
    endif
  endif
endfunction
```

Here the issue, how can I access after ``nerdtree#isTreeOpen()`` was moved in https://github.com/scrooloose/nerdtree/commit/0d88ce946fc21eca51bc1efef47ae843845e5f16?

Source: https://github.com/tony/vim-config/blob/f258b4152ddab12d066bd4310cd6a962d352a487/functions.vim#L51

**Comment by scrooloose** [comment]
Hey @tony, you should be able to use it exactly as you say via `g:NERDTree.IsOpen()`. Let me know if this isn't working as expected.

Also, you can simplify your hax0r a bit. Instead of

```
execute ':NERDTree ' . getcwd()
```
you can simply use
```
NERDTree
```
They are equivalent since `NERDTree` defaults to the CWD if no arg is given. You can also drop the `execute` at the front of some of your lines.

Here is an update version of `NERDTreeFindPrevBuf` --> https://gist.github.com/scrooloose/b3936e975c39777b1530.
