### ISSUE TITLE
Undefined variable: g:NERDTree when accessing NERDTree from vim config

### ISSUE THREAD

**Issue by tony** [scrooloose/nerdtree#449]
Re: #445 and https://github.com/scrooloose/nerdtree/issues/445#issuecomment-99579865

```viml
E121: Undefined variable: g:NERDTree
E15: Invalid expression: g:NERDTree.IsOpen()
```

Is it possible to access ``NERDTree.IsOpen()`` from our configs?

**Comment by scrooloose** [comment]
Yes this is possible. Your vimrc is loaded before any plugins (look at `:scriptnames` to see the ordering) - hence the error. The solution is to run the code after nerdtree has loaded.

There are 3 ways you could go:

1. Put your code in an autocommand in your vimrc:
    ```
    autocmd vimenter * call s:MyNerdtreeHacks()

    function s:MyNerdtreeHacks()
        ...
    endfunction
    ```
2. Put your code in ~/.vim/nerdtree_plugin/yourhacks.vim. Nerdtree sources all files in this dir after it finishes loading itself.

3. Put your code in ~/.vim/after/plugin/yourhacks.vim. The after dirs are loaded after the standard runtime dirs.

Id go with method 1 for simple hacks and method 2 otherwise. I really only mention method 3 for completeness.

HTH
