### ISSUE TITLE
To create multiple files

### ISSUE THREAD

**Issue by shinokada** [scrooloose/nerdtree#459]
Hi, 
It will be great if NerdTree can create multiple files at once.
Something like this.

```
m (to show menu)
(g)enerate multiple files
/Users/myname/dirname/file1.php file2.php file3.php file4.php
```

Is is possible?

**Comment by lifecrisis** [comment]
I believe you're better off using your shell for something like this. Brace expansion in `bash` is perfect for this kind of thing.
```bash
# Create files "file1.txt", "file2.txt", ... "file100.txt"
touch file{1..100}.txt
```
Since the feature already exists in external tools, I see little point in adding it here other than flair. This is a very low priority feature request. I vote that it be rejected.

**Comment by geoyws** [comment]
Is this still not possible today?

**Comment by PhilRunninger** [comment]
That's right. This is still something that should be done in the shell. NERDTree is already too bloated to be adding unnecessary functionality.
