### ISSUE TITLE
NERDTreeToggle command causes gVim window unsnaps from the corner and redraws itself near the centre of the screen on Windows 8.1

### ISSUE THREAD

**Issue by rishabhsagar** [scrooloose/nerdtree#513]
When using gVim snapped to one of the corners of my Windows 8.1 desktop (Windows Key + Left / Right key), if I invoke NERDTreeToggle command, the gVim window unsnaps from the corner and redraws itself near the centre of the screen.

I am having to snap gVim window back into it's corner every time I use NERDTreeToggle command.

**Comment by PhilRunninger** [comment]
This happens when gvim has scrollbars turned on. Check your `:set guioptions?`. If you see L or R, then you need to remove them.
```
:set guioptions-=L
:set guioptions-=R
```

More information, including other possible causes, on [StackOverflow](http://stackoverflow.com/questions/13251522/why-does-gvim-resize-and-reposition-itself-after-some-actions)

**Comment by scrooloose** [comment]
Thanks @PhilRunninger :)

**Comment by rishabhsagar** [comment]
Thanks Guys!  This resolved the issue.

**Comment by meldavis** [comment]
Thank you!   I'm sorry to have troubled you. .That fixed it perfectly.

**Comment by gomezhyuuga** [comment]
Thanks @PhilRunninger !
This tip should be in the FAQ or something like that >.<
