### ISSUE TITLE
Can't reopen after use 'x' while the directory only have one child directory.

### ISSUE THREAD

**Issue by xinyifly** [scrooloose/nerdtree#519]
/a
/a/b
/a/b/c
/a/b/d
So, I open a. Get 'a/b', list 'c,d'.
Then, I close using x. Get 'a'
After, can't reopen 'a'.

**Comment by czak** [comment]
I'm having the same issue. After closing a "cascade" dir via <kbd>x</kbd>, it won't show the contents anymore.

Here's an asciicast displaying the issue:

<a href="https://asciinema.org/a/ef4wk8hz5mk9hub6msjlaflvb" target="_blank"><img src="https://asciinema.org/a/ef4wk8hz5mk9hub6msjlaflvb.png" /></a>

The issue can be somewhat resolved by setting:

```
let NERDTreeCascadeOpenSingleChildDir=0
```

...however this disables the automatic cascade open (as per the option name), which is convenient for e.g. Java projects.

**Comment by czak** [comment]
I've been trying to track down this issue.
I don't have a fix yet, but before I forget here are my notes.

(please excuse imprecise terms, Vimscript is new to me)

The difference I'm seeing **before** and **after** closing a cascade node with `x` manifests here:

https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/ui.vim#L443

The output of `self.nerdtree.root.renderToString()` **before** `x`-ing the `c` node is:

```
▾ a/b/
    c
```

The output of `self.nerdtree.root.renderToString()` **after** `x`-ing the `c` node is only:

```
▾ a/b/
```

(the nodes I'm referring to are the `a/b/c` folder structure as linked in my asciicast).

I believe some of the flags set on the nodes during [closeCurrentDir](https://github.com/scrooloose/nerdtree/blob/master/autoload/nerdtree/ui_glue.vim#L186-L205) prevent the last child from being rendered.

I'll do some more digging, but maybe this helps someone.

**Comment by czak** [comment]
If someone could help me how to set a breakpoint on this particular function, that would be great:

https://github.com/scrooloose/nerdtree/blob/master/lib/nerdtree/tree_file_node.vim#L325

My current solution is:

* I turned the script-local `s:activateDirNode` into a global `nerdtree#ui_glue#activateDirNode`
* I set `:breakadd func nerdtree#ui_glue#activateDirNode`
* I step through until I reach that line
This is a PITA

`TreeFileNode.renderToString` is different because it's in the dictionary an I can't seem to get a breakpoint in there.

**Comment by scrooloose** [comment]
Fixed by @czak's pull request.
