### ISSUE TITLE
Files do not appear in the folder.

### ISSUE THREAD

**Issue by dgorodnichy** [scrooloose/nerdtree#526]
Hello. Files do not hidden, but when I open folder it looks empty. When I explore empty dir, files displayed (right column on attached image). After reloading vim files are displayed.

![2fd1773ad3](https://cloud.githubusercontent.com/assets/871518/12033090/6b287f40-ae30-11e5-8357-ba814be8ee97.jpg)

**Comment by dunst** [comment]
Update: This only happens after I press "x" on folder.

**Comment by chrisyue** [comment]
+1
same issue

**Comment by igkuz** [comment]
+1 the same problem

**Comment by Hates** [comment]
+1 Same problem

**Comment by iamcco** [comment]
+1 Same problem

**Comment by athallas** [comment]
Duplicate:  #519 
Same issue.

**Comment by noscripter** [comment]
The problem still exists.

**Comment by mzavoloka** [comment]
I experience this bug when I go up twice from a directory that is a single item in its parent directory.

For example (as shown on OP's screenshot), I open vim from directory controllers/admin. Then I press 'u'. And then I press 'u' again. At this step I see the directory structure like on the screenshot (>controllers/admin). And I'm not able to view the contents of controllers/admin even if I press 'R' or 'r'.

#519 is a bit different issue. I have updated to the latest version at the moment.

**Comment by mzavoloka** [comment]
mkdir ttt
mkdir ttt/ttt/
touch ttt/ttt/test
cd ttt/ttt/
vim test

Inside vim:
:NERDTreeToggle
u
u
And now you're not able to view the folder ttt/ttt.

**Comment by lifecrisis** [comment]
I can now replicate this bug, and I believe it to be confirmed. Replicate by...

1. Point the NERDTree root to a directory that will cascade beneath its parent.
2. Press `u` twice.
3. Note that the cascaded directory will no longer open.

You can do this in the NERDTree repository itself by making the root `nerdtree/lib/nerdtree/` pressing `u` twice, and then trying to open `lib/nerdtree/` again.

Bug confirmed.

**Comment by PhilRunninger** [comment]
Look at the `NERDTreeCascadeSingleChildDir` option. When set to 1, the default, I see the behavior described in this issue. A workaround is to set it to 0.

**Comment by lifecrisis** [comment]
Hey, @PhilRunninger, I think I've got this one. A possible duplicate is issue #547. I also have a fix in progress. I believe the problem can be captured in a few words as follows:

When you make a directory that belongs to a cascade the NERDTree root, pressing `u` repeatedly will close every directory in the chain along the way up. Then, when you try to open the cascaded node with `o`, the mapping opens the lowest directory node in the cascade while *leaving the ancestor nodes closed*. That is, the mappings are operating on the tail of the cascade, not the immediate child of the current root node.

The rendering logic never reaches open node at the bottom of the cascade, and the children there aren't displayed because their ancestors are "closed" from the point of view of the NERDTree. This also explains why the open/closed status indicator (`+` or `~` on Windows) changes while the children never render.

**Comment by lifecrisis** [comment]
**ANNOUNCEMENT:** Everyone experiencing this bug can try the fix in pull request #720. It should repair this problem without any side effects. The code is currently under review.

**Comment by mzavoloka** [comment]
Works for me, thx.
