### ISSUE TITLE
FTP - feature request?  difficult?

### ISSUE THREAD

**Issue by chrisputnam9** [scrooloose/nerdtree#534]
I'd be really interested in using NerdTree to browse/edit files over FTP.

I might even look into doing this myself, but figured I'd check first:
- Is something that might be added as a feature?
- Is there anything I'm unaware of that would make this difficult/impossible?

**Comment by hauleth** [comment]
Why not use FTPFS?

**Comment by chrisputnam9** [comment]
Hmmm.... not a bad option at all.  Thanks!

**Comment by chrisputnam9** [comment]
Update - I've been using FTPFS for a while now.  It is a very nice solution **iff** the FTP server is decent.  Since I connect to a lot of servers, sometimes it means I just can't use it - too slow - and I have to resort to something inferior.  So, I'm reopening this with my original question.  Could there be a way to integrate this?

**Comment by lifecrisis** [comment]
It's been a while since this issue was raised.  Sorry for the delay.

I don't think that integrating this functionality into the NERDTree would be easy at all.  In fact, it would add a lot of code to the NERDTree.  This would lead to a lot of bugs and expenditure of development effort.  It's hard for me to say that it's definitely worth it...

I see you've tried FTPFS.  Using an external tool like this seems to be a good solution in most cases, and it's what I would recommend.  Other options are available (e.g., SSHFS).  If you can't get a good connection with an external tool, I'm not sure how the NERDTree would be a better place to do this work.

Closing due to difficulty and issue age.

**Comment by chrisputnam9** [comment]
I understand - thank you for the response!
