### ISSUE TITLE
Dir arrows not functioning properly

### ISSUE THREAD

**Issue by fungl164** [scrooloose/nerdtree#537]
Using any of these in .vimrc
```code
let g:NERDTreeDirArrowExpandable = ' '
let g:NERDTreeDirArrowCollapsible = ' '
```
Or
```code
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeDirArrowCollapsible = ''
```
causes NERDTree not to expand after two levels.
<br>
On the other hand, using
```code
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '-'
```
causes 
```code
E16: Invalid range
E16: Invalid range
E475: Invalid argument: NERDTreeFile  #^[^"\.-+] *[^-+]*# contains=NERDTreeLink,NERDTreeRO,
NERDTreeBookmark,NERDTreeExecFile
```

**Comment by adityanatraj** [comment]
I had the same issue. As a temporary solution, I've been using `"X"` for Exapandable and `"O"` for Collapsible. 

Looking at the way the regular expression (`#^[^"\.-+] *[^-+]*#`) is being generated [here](https://github.com/scrooloose/nerdtree/blob/master/syntax/nerdtree.vim#L31), it would break the generation to use the `-` character. 

Within `[ ]`'s, the `-` is a protected character meaning "a range of characters" (like `0-9`, `a-z`, etc). Since, the expansion doesn't worry about _escaping_ (that is to inform the code that this letter is used as-is by prepending a `\`), using the `-` as either the expanding or collapsing character would be no good. In fact, any regex special character or term would be a bad choice.

I don't really know any vimscript, so I can't fix it, but that's the (or an) issue methinks.

**Comment by mdu4rt3** [comment]
Please bring back the option

let g:NERDTreeDirArrows=0

This used to work fine, now it's gone, not sure why it was removed.

**Comment by xiongm** [comment]
on the latest version, same error. annoying

Error detected while processing dotfiles/vim/plugged/nerdtree/syntax/nerdtree.vim:
line   31:
E16: Invalid range
E475: Invalid argument: NERDTreeFile  #^[^"\.-+] *[^-+]*# contains=NERDTreeLink,NERDTreeRO,NERDTreeBookmark,NERDTr
eeExecFile

**Comment by DeepikaNR** [comment]
Namaste Folks, 

Firstly, Congo on awesome work!!
I faced similar issues as elicited above but upon mapping to '>' and '<' things seem to be working fine.

Happy coding!

**Comment by igorpetrov** [comment]
I'm really waiting this to be fixed.

**Comment by pwzgorilla** [comment]
+1

**Comment by adityanatraj** [comment]
I created a PR to address this issue, it just never got a +1 or was merged in.

You can see it here: https://github.com/scrooloose/nerdtree/pull/548

**Comment by durgaswaroop** [comment]
I have the same issue and @adityanatraj's PR [here ](https://github.com/scrooloose/nerdtree/pull/548/files)solved my problem. All you have to do is find the following line
`let s:dirArrows = escape(g:NERDTreeDirArrowCollapsible, '~').escape(g:NERDTreeDirArrowExpandable, '~')`
in `nerdtree/syntax.vim` file and change it to
`let s:dirArrows = escape(g:NERDTreeDirArrowCollapsible, '~]\-').escape(g:NERDTreeDirArrowExpandable, '~]\-')`

This will fix the issue.
