### ISSUE TITLE
"3 file(s) could not be loaded into the NERD tree" on Windows gVim

### ISSUE THREAD

**Issue by Asheq** [scrooloose/nerdtree#587]
I'm using gVim version 7.4.

Whenever I open NERDTree in my home directory, I get the following error:

> NERDTree: 3 file(s) could not be loaded into the NERD tree

I compared the files NERDTree was displaying with what the "ls" shell command was displaying, discovering that the 3 files NERDTree could not load were:
- NTUSER.DAT
- ntuser.dat.LOG1
- ntuser.dat.LOG2

PS: I'm not the only one with this problem. Someone else posted [this ](http://stackoverflow.com/questions/33848305/nerdtree-gives-error-x-files-could-not-be-loaded-into-the-nerdtree) stack overflow question.

**Comment by stefanqin** [comment]
I'm also getting this error. Using sudo works for some reason, however it's awfully inconvenient having to sudo every time, especially on my cygwin setup. Help?

**Comment by arcadesdude** [comment]
Same problem for me (Win10, gVIM) I just hid the error message on startup:
autocmd VimEnter * silent NERDTree / | wincmd p

**Comment by ashergarland** [comment]
I'm on Win10 and I see this a lot because these files exist in `%USERPROFILE%`. I think this is happening because these apps require administrative privileges in order to view these files. Even if your `cmd` window is opened elevated, NerdTree doesn't get these privileges. 

Using this command hides the files, but the errors still occur:

> let NERDTreeIgnore = ['\*ntuser*','\NTUSER.DAT']

I would expect ignoring the files to stop NerdTree from trying to load these files, but it seems as though that how the ignore works is that it loads all the files and then just hides the ones that match the ignore list.

**Feature request**: The command `NERDTreeIgnore` should stop NerdTree from attempting to load files in the ignore list.

**Comment by Chinggis6** [comment]
let NERDTreeIgnore = ['\.DAT$', '\.LOG1', '\.LOG1'] should do it.

You can also extend it to ignoring other otherwise unloadable files such as multimedia files and so:

    let NERDTreeIgnore = ['\.png$','\.jpg$','\.gif$','\.mp3$','\.flac$', '\.ogg$', '\.mp4$','\.avi$','.webm$','.mkv$','\.pdf$', '\.zip$', '\.tar.gz$', '\.rar']

**Comment by FireInTheWall** [comment]
I met this issue and it appears everytime I use "u" to switch the root dir to the parent dir of the current dir.

**Comment by PhilRunninger** [comment]
Those are system file that Windows doesn't let you read. When NERDTree is reading any directory, it treats un-`filereadable()` files as an error condition, counts them, and omits them from the tree. This happens before files are ignored, so that you can toggle the ignored files on and off later; see `:h NERDTree-f`. Ignoring those three specific files will do no good because they are never put in the tree anyway, but I've found it useful to ignore the other NTUSER files since I have no need to edit them.
```
let NERDTreeIgnore=['\c^ntuser\..*']
```

I agree that the error message is a little unnerving, but it's working properly. In the case of NTUSER files, I'd rather not see the message, but there may be other cases where it's important to see it. Knowing the difference between those situations is likely impossible.

I'm going to close this issue. If there is a specific request for a change, please open a new issue.

**Comment by ashergarland** [comment]
Why does nerdtree try to read the file when all it really needs is the file name? It should display the files names in the directory and only try to read the contents when the user selects those files to display. At that point it should display an authorization, or unable to read, error.

**Comment by PhilRunninger** [comment]
It's not reading the file, only checking whether it's readable. In *nix, I assume it uses the permissions `-rw-r--r--`, and I'm not sure how it's done in Windows, but studying the vim source code for `filereadable()` should shed light on those details. Since NERDTree is a plugin for a text editor, it doesn't make much sense to show a file in the tree that you cannot edit, and I have no desire to change that behavior at this time.
