### ISSUE TITLE
Hide * in executable files

### ISSUE THREAD

**Issue by tiagofumo** [scrooloose/nerdtree#590]
Is there any configuration to hide the * in executable files on NERDTree? Do they come from NETrw? I saw the source code of NETrw and doesn't look like there is any configuration available to hide them. They cause bugs in some nerdtree plugins.

**Comment by PhilRunninger** [comment]
@tiagofumo , take a look at the referenced pull request, #604, and give it a thumbs up if it fits your needs.

**Comment by PhilRunninger** [comment]
@tiagofumo , what bugs are being caused by the * on executable files? Is it related to your [vim-nerdtree-syntax-highlight](https://github.com/tiagofumo/vim-nerdtree-syntax-highlight) plugin? As @scrooloose has said in other comments, he is loathe to add more options to the code, preferring to offload such changes to NERDTree plugins. With that in mind, I'd like to see if there is a way to do that instead of merging my pull request #604.

**Comment by tiagofumo** [comment]
@PhilRunninger the problem was that my plugin didn't handle the syntax for executable files (which is NERDTreeExecFile instead of NERDTreeFile) and the * at the end. But the new version can handle this problem. So for now I am okish... even though I think it is not that great to have a * and a different syntax for executable files in general.
