### ISSUE TITLE
Marking items to move or copy in the tree

### ISSUE THREAD

**Issue by matthsims** [scrooloose/nerdtree#60]
I was thinking that it would be pretty darn convenient if NERD had a better move/copy system. Scrolling down the tree with j&k, mark one or more items with some key, perhaps shift M, then if I want to move or copy all of them I move my cursor to the destination directory and press whatever hotkey, like C or V.
Mainly, I think the current way to copy or relocate files is a pain, and I end up switching to a shell to do it most of the time.

**Comment by iwkse** [comment]
\+ 1

**Comment by PhilRunninger** [comment]
I've written another plugin to do this, although it uses a visual selection instead of marking files with a keystroke. Its URL is https://github.com/PhilRunninger/nerdtree-visual-selection, and it will open all the files in a visual selection (in either the previous window, in horizontal or vertical splits, or in tabs). It can also delete all the files in a visual selection, after confirmation.

It doesn't handle moving/copying files, but I'll accept PRs in either repo to improve that functionality.
