### ISSUE TITLE
How to disable a NERDTree mapping that conflicts with a custom mapping?

### ISSUE THREAD

**Issue by wwselleck** [scrooloose/nerdtree#605]
I currently have this mapping in my .vimrc to make navigating between windows easier.

`nnoremap <c-j> <c-w>j`

I noticed that after installing NERDTree and opening it in the current buffer with e ., I couldn't use `c-j` anymore to move down to below window. I took a look at the NERDTree docs and found this mapping

`<C-J>...Jump down to the next sibling of the current directory...|NERDTree-C-J|`

I don't really see myself using this mapping, so how could I disable it and go back to `<c-j>` doing `<c-w>j`?

**Comment by PhilRunninger** [comment]
@wwselleck, use NERDTree's customizability to your advantage. Put these lines in your vimrc to effectively disable the functionality:

```
let g:NERDTreeMapJumpNextSibling="☻"
let g:NERDTreeMapJumpPrevSibling="☺"
```

You can use any string or keystroke that you're unlikely to type in the NERDTree window. I picked the smiley faces because I know of no way to type them in Normal mode. I'd experimented with an empty string, and it worked, but I was concerned there would be unintended consequences. Long strings of random characters would also work, but they look ugly.

**Comment by MoezGholami** [comment]
Thanks @PhilRunninger 
An effective dirty hack :)
