### ISSUE TITLE
Create file (m ↦  a) does not trigger BufNewFile

### ISSUE THREAD

**Issue by aperezdc** [scrooloose/nerdtree#617]
When using the “Create file” method (keys `m` ↦ `a`), it seems that NERDtree first creates an empty file, and then opens the empty file. This creates and opens the file in Vim _without_ triggering the `BufNewFile` event.

In particular, this breaks using the `vim-templates` plugin, please check the discussion on aperezdc/vim-template#17 for more details.

**Comment by PhilRunninger** [comment]
@aperezdc, the fs_menu.vim NERDTree plugin is meant to be analogous to the file operations one would do by right-clicking in Windows Explorer. The difference here is between creating a file on disk first, and creating an empty buffer directly in vim. The latter triggers BufNewFile; whereas, opening a file will fire the BufReadPost. I took a look at the code for vim-template's [TLoad function](https://github.com/aperezdc/vim-template/blob/master/plugin/templates.vim#L418). It looks like it's already doing a check to make sure the buffer is empty. What happens if you modify the autocmd to trigger on BufReadPost also, like this?

```
if !g:templates_no_autocmd
	augroup Templating
		autocmd!
		autocmd BufNewFile,BufReadPost * call <SID>TLoad()
	augroup END
endif
```

The other option, as you [mentioned](https://github.com/aperezdc/vim-template/issues/17) is to write your own function using NERDTree's API.
