### ISSUE TITLE
How to remove DIR arrows since NERDTreeDirArrows option has been removed?

### ISSUE THREAD

**Issue by cj** [scrooloose/nerdtree#636]
How would you remove the DIR arrows now that the `NERDTreeDirArrow` option has been removed?

**Comment by osDanielLee** [comment]
It's very weird, why you need to remove it? If the reason you want to remove arrows is messy code happened, I will suggest you to define the arrows in your .vimrc file:
`
let g:NERDTreeDirArrowExpandable = '+'
let g:NERDTreeDirArrowCollapsible = '~'
`
This may help you solve your problem better than delete DIR arrows code.

**Comment by PhilRunninger** [comment]
You can use a non-breaking space to make the arrows appear to have been removed. Regular spaces won't work, as they causes keypresses on lower-level directories to not be recognized. Here are the **keystrokes** you need to type in **Insert** mode as you put these lines in your .vimrc:

```
let NERDTreeDirArrowExpandable = "<C-V>u00a0"<CR>
let NERDTreeDirArrowCollapsible = "<C-V>u00a0"
```

The resulting strings look like a single space, but they don't interfere with the keypresses on directories.

**Comment by cj** [comment]
@PhilRunninger that did the trick.  Thank you!.

@osDanielLee I don't need the arrows when using https://github.com/ryanoasis/vim-devicons

**Comment by taq** [comment]
Weird, I get a ']' char in front of the filename when I use this option with the "<C-V>u00a0".

**Comment by PhilRunninger** [comment]
@taq, I suspect this may be a font issue, although all modern fonts should have a non-breaking space in them. What value do you have for `:set encoding`? If I switch mine to `latin1`, then `u00a0` shows up as a vertical bar. I'm not sure what else to suggest. Maybe someone else has an idea on this one.

**Comment by taq** [comment]
Hey @PhilRunninger ! Thanks for your answer!

I'm using `utf-8` as encoding and a patched version of FiraCode. Will try to find what is happening there. :-)

Thanks again!

**Comment by kutsan** [comment]
@taq Did you find out? I am now having the same problem with Fira Code.

**Comment by taq** [comment]
@kutsan no, I just gave up since it was taking some time.

**Comment by kutsan** [comment]
@taq I finally kind of found the problem under vim-devicons source code. I don't know how, vim is unable to apply `syntax match` for that bracket [here](https://github.com/ryanoasis/vim-devicons/blob/17199e322f69cabff9292c3e81d963d212376c34/plugin/webdevicons.vim#L372) because [their utility function return](https://github.com/ryanoasis/vim-devicons/blob/17199e322f69cabff9292c3e81d963d212376c34/plugin/webdevicons.vim#L645-L653) zero-width space character. Maybe since it's zero-width space, the character after that isn't considering a syntax item? My solution is to remove `artifactFix` variable [in this line](https://github.com/ryanoasis/vim-devicons/blob/17199e322f69cabff9292c3e81d963d212376c34/plugin/webdevicons.vim#L653), make it simply `return symbol`.

By the way, can you take a look @ryanoasis? You should add a couple of `if has('gui_running')` there.

**Comment by kutsan** [comment]
@ryanoasis Did you know the reason why people are seeing that closing bracket before I told you? Because you should at least have added a flag there or add a question under FAQ; I was looking for the solution for hours, you should blush more! ><

**Comment by ryanoasis** [comment]
@kutsan 

> Did you know the reason why people are seeing that closing bracket before I told you? 

I was aware of the problem (a few reports about it) but I did _not_ know it was related to the `artifactFix`

> Because you should at least have added a flag there or add a question under FAQ

If I would have known I definitely would have made it configurable in hindsight, it was a bit of a hacky/rushed fix. I really do try to put a lot into the Wiki and FAQ but it's been my experience it doesn't really help most new issues or even old issues not all will take the time to look.

> I was looking for the solution for hours, you should blush more!

I really do understand that frustration and sorry you had to spend so much time figuring it out. Especially since it does sound like you did check the appropriate places (FAQ, etc.)

**Comment by kutsan** [comment]
> I really do understand that frustration and sorry you had to spend so much time figuring it out. Especially since it does sound like you did check the appropriate places (FAQ, etc.)

It's okay, I wasn't really that serious about blushing. Thanks for you answers and attention.

> I really do try to put a lot into the Wiki and FAQ but it's been my experience it doesn't really help most new issues or even old issues not all will take the time to look.

Yeah, I feel you; but you did your job, it's their problem for not looking into your resources.

By the way, your [See FAQ](https://github.com/ryanoasis/vim-devicons#faq--troubleshooting) link is broken.

**Comment by ryanoasis** [comment]
@kutsan Ah okay gotcha :smile: it can be hard to know online.

Thanks for heads up on the link, just fixed it :+1:

**Comment by kutsan** [comment]
@chbroecker We need to see your code first. Could you please collaborate on that?

**Comment by chbroecker** [comment]
Sorry here is my .vimrc:
https://github.com/chbroecker/dotfiles/blob/master/vim/.vimrc 

If I uncomment lines 65 and 66 I get the behavior from the screenshot above.

**Comment by PhilRunninger** [comment]
@chbroecker , My guess is you copied the text from my comment above, instead of typing it. Since then I've learned an easier way that doesn't involve using `Ctrl+V`.
```
let NERDTreeDirArrowExpandable = "\u00a0"
let NERDTreeDirArrowCollapsible = "\u00a0"
```
A recent pull request now also requires you to set another variable if you have the above settings. The non-breaking space is, by default, now used to surround the filename so it can be accurately parsed from the line of text. If you use `"\u00a0"` in place of your arrows, you need to use a different character for that delimiter. Also add this line to your vimrc:
```
let NERDTreeNodeDelimiter = "\x07"
```

**Comment by chbroecker** [comment]
I actually did type it out but missed the part about the keystrokes. I somehow thought the <C-V> had to be in there. 

Thank you very much though, now everything is working fine. :)

**Comment by ray-lab** [comment]
How about the following settings

```
let g:NERDTreeDirArrowExpandable = "\u00a0"
let g:NERDTreeDirArrowCollapsible = " "
```

My vim no longer displays `]`.

I do not know why it works 😅

**Comment by Dmitra** [comment]
> You can use a non-breaking space to make the arrows appear to have been removed.

Can we please reopen this issue, as while, arrows are not visible, they are not removed and still take entire column of space

**Comment by PhilRunninger** [comment]
Please open a new issue. Reference this one, and provide all the information asked for in the issue template.

**Comment by PhilRunninger** [comment]
If anyone is still following this, take a look at the latest version of NERDTree (6.6.0). Pull request #1085 added the ability to completely remove the arrows. If you use the following lines in your .vimrc, the entire tree will be shifted to the left two character positions.
```
let g:NERDTreeDirArrowExpandable = ''
let g:NERDTreeDirArrowCollapsible = ''
```
