### ISSUE TITLE
Opens new file as tab, but cannot go navigate to it

### ISSUE THREAD

**Issue by degva** [scrooloose/nerdtree#639]
Hello!

Every time I open a second file with nerdtree (pressing enter), it goes to a new tab (or what it seems to be a tab). Checking on :buffers gives me effectively all the files I've opened, but I cannot navigate them with gt/gT. 

Also, if I try to close one of the "tabs" with :q and Nerdtree closed, it closes all the buffers, exiting neovim.

Finally, if I open the files with "t" instead of "enter" I can navigate to these files gt/gT, but if I mistakenly open another file with enter, it opens a another buffer that I cannot close. without closing as well the other buffer where I was at the moment I opened the second one. The tabs does not close. 

I'm using neovim and archlinux and plug to install nerdtree. And I've mapped Nerdtree to open with F3.

Thanks!

**Comment by lifecrisis** [comment]
It really seems you're confused about how Vim works... I'm unable to follow the description of your issue.  I suggest you continue to read the documentation and try things out. In the future, please provided enough information so that we can reproduce your issue precisely.

This issue is quite old, so I will now close.
