### ISSUE TITLE
Feature Request:  improve efficiency and save last leave status in project dir.

### ISSUE THREAD

**Issue by pangchol** [scrooloose/nerdtree#641]
1. nerdtree cost more time in the document more slowly, the performance issues seem to be more than 100 in the document on the performance of a bit obvious, performance problem in "recursively opening node" is most obvious. I want know nerdtree is there room for performance optimization.
2. Each time the project is open nredtree will always shut down the directory to the state, I think if nerdtree can save status every time to leave the current directory and automatically load restore, it will be a very useful feature.

**Comment by alexander-alzate** [comment]
+1
It would be great if NERDTree implements asynchronous reloads of the tree by using jobs.

**Comment by lifecrisis** [comment]
@pangchol, your suggestion is noted. Better performance is always better.

1. Recursively opening a node is a user's decision. Press `Ctrl-C` to interrupt this process if it's taking too long. We won't dictate to Vim users what "too long" means.
2. Saving the project structure as you suggest doesn't help because it still needs to be validated again later (when the NERDTree is opened). This means that we might as well just create it again on the fly.

@alexander-alzate, you suggest a difficult path here. Asynchronous operations are very new in Vim and are difficult to wrangle. Maybe one day...

Thanks to you both, but this issue is closed.
