### ISSUE TITLE
NERDTree window resizing when equally resizing splits is if you've previously used Ctrl-w 'o' to maximize a split

### ISSUE THREAD

**Issue by theirishpenguin** [scrooloose/nerdtree#644]
**Note:** Originally posted as a StackOverflow issue at http://stackoverflow.com/questions/41014553/is-it-possible-to-stop-the-nerdtree-window-resizing-when-using-ctrl-w-equals-to/41014785#41014785

**Steps to reproduce**

Set up 4 splits, along with the NERDTree window on the left like this...

```
    |--|-----|-----|
    |  |     |     |
    |NT|-----|-----|
    |  |     |     |
    |--|-----|-----|

```

Do a Ctrl-w followed by 'o' to maximize a split.

Do a Ctrl-w followed by 'o' to unmaximize a split.

Do a Ctrl-w followed by '=' to equally resize splits 

I end up with this...

```
    |-----|-----|-----|
    |     |     |     |
    |  NT |-----|-----|
    |     |     |     |
    |-----|-----|-----|
```

That's not the end of the world. The real problem is when I close a couple of splits it ends up like this...

```
    |--------|--------|
    |        |        |
    |   NT   |--------|
    |        |        |
    |--------|--------|
```

... which is unusable and I have to exit Vim and start over.

**Comment by theirishpenguin** [comment]
UPDATE: I noticed that when the problem happens, if I enter the NERDTree split and run ":set winfixwidth" that it will prevent the NERDTree resize until the next time I do "maximize split" followed by an "equal resize".

**Comment by theirishpenguin** [comment]
The best current workaround I have is to add the following to my .vimrc

nmap <F9> :vertical resize 40<CR>:set winfixwidth<CR>

... and when the above problem occurs then I position the cursor in the NERDTree window and hit F9.

**Comment by lifecrisis** [comment]
Hey @PhilRunninger, you might think this is interesting...

There is nothing here that indicates a problem with the NERDTree.  I researched this problem, and it turned out that there was a bug with Vim, itself.  In effect, the `'winfixwidth'` and `'winfixheight'` options were not always respected by commands that close windows.

I wrote up a patch that fixes this problem and submitted it today: [patch 8.0.1790](https://github.com/vim/vim/commit/c136af29c0b1939076fbae7d36afd90dce740315).  It was accepted by Bram, so new versions of Vim will not have this problem.

Thanks for bringing this to our attention!
