### ISSUE TITLE
Nerdtree in ubuntu 16.04 doesn't work

### ISSUE THREAD

**Issue by chenziliang** [scrooloose/nerdtree#656]
<img width="234" alt="screen shot 2017-01-27 at 2 26 54 pm" src="https://cloud.githubusercontent.com/assets/775911/22362368/1a8f4268-e49d-11e6-90e7-31672c21934f.png">

As above screenshot shows, i can't enter the subdirs. Not sure why is showed "V?" at the beginning of the subfolders

**Comment by PhilRunninger** [comment]
My first guess is you're using a font that doesn't render the arrows correctly. Try changing the font, and see what happens. Are you setting any NERDTree variables in your vimrc? Try putting the following lines in your vimrc to see if it solves the problem. It will tell us if the problem is with the font.
```
let NERDTreeDirArrowExpandable = "+"
let NERDTreeDirArrowCollapsible = "~"
```
I don't have access to Ubuntu, so I welcome comments from others who do.

**Comment by chenziliang** [comment]
Thank Phil. After applying the above lines in .vimrc, it works.
