### ISSUE TITLE
Is there any shortcut to toggle between my editor screen and nerd-tree tab in vim?

### ISSUE THREAD

**Issue by balogic** [scrooloose/nerdtree#663]

**Comment by lifecrisis** [comment]
As you noted there are plenty of ways to map this kind of behaviour yourself. Mapping `<C-N>` is already mentioned in the `README.markdown` file, and the newly documented `:NERDTreeFocus` command can be used for this purpose as well.

These types of maps are really up to the individual user, so you'll have to experiment with the macros that you might want. Generally, that will be some combination of mappings involving `:NERDTreeToggle` and `:NERDTreeFocus`.

I'm recommending to @PhilRunninger that this issue be closed since no real issue with the NERDTree is reported here.
