### ISSUE TITLE
Do I need pathogen.vim or apt-vim to install?

### ISSUE THREAD

**Issue by anongh** [scrooloose/nerdtree#668]
I know this is a strange question.
But I want to know clearly.
I hope to be more accurate about the installation.

**Comment by PhilRunninger** [comment]
One answer to your question is: **No**. You could clone the repo, but then you'd have to either 
1. move files from the repo into the correct subfolders in your ~/.vim folder, or
1. modify your runtimepath variable so that vim sees these folders when you try to run NERDTree.

The better answer is: **Yes**. A plugin manager definitely simplifies the process of installing, updating, activating or deactivating plugins. I used pathogen and then Vundle for a while, but finally settled on vim-plug as my favorite. According to the README for apt-vim, it requires you to also install pathogen. There is a good discussion on Stackoverflow - http://vi.stackexchange.com/questions/388/what-is-the-difference-between-the-vim-plugin-managers - describing the differences between these and other plugin managers, including the fact that pathogen technically doesn't manage plugins at all. Pathogen just manages the runtime path, while apt-vim puts a plugin manager on top of it, if that makes sense. Vundle and vim-plug have both capabilities rolled into one package.

I like vim-plug because it's somewhat small, and it allows me temporarily to disable a plugin (for debugging, perhaps) by commenting a line in my vimrc; I don't need to delete the repo, only to re-clone it when I want it back.

**Comment by anongh** [comment]
Thank you for your faithful answer.

Because of the neotree bug, all the package managers I installed (vim-plug, Vundle, Pathogen) do not work. :(
So I installed it manually and I just succeeded.

I did not know the difference between the managers, but once the neotree bug is fixed, I'll try to re-run vim-plug as you said. Thank you.
