### ISSUE TITLE
Provide adequate defaults

### ISSUE THREAD

**Issue by avesus** [scrooloose/nerdtree#732]
I've spend the whole day writing config where things will be working in an expected way.

You can consider my config as hint to improve things in the future and include those in one of new versions: https://gist.github.com/avesus/1954d9384d86cc1e39cb2b2eff7017b7

I love NERDTree! Thank you for your hard work!

**Comment by PhilRunninger** [comment]
I am going to suggest closing this issue. The changes/customizations you are requesting are done exactly where they should be done - in the `.vimrc` file. Making NERDTree more like Visual Studio is not something the collaborators are interested in pursuing. @lifecrisis, do you concur?

I encourage you to keep learning Vim and NERDTree, and to continue refining your `.vimrc`, as you will no doubt find issues with it (we all do). One thing I noticed right away was your use of `:wincmd w` in the `<C-N>` and `<C-D>` mappings. It does not guarantee you would end up in NERDTree on the file you're editing. You're better off using `:NERDTreeFind` instead; otherwise, you could delete the wrong file or create a new one in an unexpected location.

**Comment by lifecrisis** [comment]
I'm in agreement with you, @PhilRunninger. Thanks for your work, @avesus, but it isn't really the kind of thing that is of use to us. Everyone has their own way of using the NERDTree effectively, and we can't be opinionated about this without potentially breaking user configurations related to *other* plugins or features.

**Comment by avesus** [comment]
Thanks for your response! I'm super thankful for what you've created! Works very robust, and my productivity and convenience rose a lot comparing to Ctrl+Z ls - la fg etc.

Since I wrote the config, it works on all my machines and VMs without any bugs. Very stable product!
