### ISSUE TITLE
Remove option to hide files

### ISSUE THREAD

**Issue by dead10ck** [scrooloose/nerdtree#746]
There is currently an option to hide files by pressing `F`. Seeing as the whole point of this plugin is to be a *file navigator*, I'm having trouble understanding why this even exists, or what the use case is. Additionally, more often than I care to, I accidentally press `F` and suddenly all the files disappear, I have no idea what just happened, and when I figure it out, I have to hit `?` to find what the shortcut is again to see my files. Please consider removing this option.

**Comment by lifecrisis** [comment]
This is actually a useful default mapping.  If you're a sys-admin who browses directories with hundreds of files and sub-directories, sometimes you want to limit consideration visually to only the directories that are present and ignore the files (this has helped me write more than a few scripts).

You can disable the mapping in your `vimrc` file with the following line...

```viml
let g:NERDTreeMapToggleFiles = ''
```

You should then no-longer be bothered by this mapping.

Since this issue does not identify a bug or documentation error, I will now close.

**Comment by PhilRunninger** [comment]
I think an empty string doesn't work. Try using a key you don't use, or one that is impossible to type, like a Unicode character not on the keyboard.

**Comment by lifecrisis** [comment]
Hmmm... I tested it and had no issue with an empty string.  It could be a platform issue... interesting if it is.

If you have problems @dead10ck, definitely try @PhilRunninger's suggestion.

**Comment by dead10ck** [comment]
@lifecrisis I see. Alright, thanks for the tip, I'll try that out.

**Comment by PhilRunninger** [comment]
@lifecrisis, I found my original post on this topic: #605. It was more of a suspicion that an empty string would cause bad behavior. I think there must have been something in the code to make me think that.
