### ISSUE TITLE
Feature request: To be able to change the bookmark arrow icon

### ISSUE THREAD

**Issue by TomatoMus** [scrooloose/nerdtree#789]
Currently, the directory icon can be changed.
```
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
```
However, can not change the arrow icon(>) of bookmark.
I'm glad that there is an option to change the icon of bookmark.
https://github.com/scrooloose/nerdtree/blob/e2a9929bbea0ec2050f2ea44b7e7bae3ccac66e6/lib/nerdtree/bookmark.vim#L292

**Comment by lifecrisis** [comment]
I don't see the need in this.  It's an additional option that doesn't improve the functionality of the bookmarks feature in any measurable way.  What I would like to see is numbers instead of icons... this would allow the user to press `B` and then use `<Number>j` to jump to a specific bookmark.  That may be added in the next version of the NERDTree.
