### ISSUE TITLE
NERDTreeFind closes all currently expanded nodes in the tree view.

### ISSUE THREAD

**Issue by joel1st** [scrooloose/nerdtree#793]
This appears to have been introduced by the recent `NERDTreeFind` refactors/bug fixes.

When calling `NERDTreeFind` on a particular buffer, the current state of expanded nodes in the tree are lost and only the current buffer is expanded. This can be jarring and disrupt certain workflows.

To recreate the issue:
Expand a few sibling folders of where the buffer that you want to call `NERDTreeFind` on is located.
Call `NERDTreeFind` on said buffer.
Observe that the buffer's folder has been correctly expanded, but the sibling folders have been closed.

**Comment by lifecrisis** [comment]
I noticed this myself after using the fix I created for another bug.  I was just waiting to see if anyone complained before dealing with it.  I admit that it was inadvertently introduced.

Ideally, we would fix both problems... Worst case, we can just revert the changes (`:NERDTreeFind` has another problem that is fixed with a PR that is waiting review).  Going back to the previous functionality wouldn't be hard.  The fix that introduced this was debatable anyway...

@PhilRunninger, some good changes were made in PR #785. We don't need to lose all of them, but it would be easier to revert the main change from that PR.  What do you think?

**Comment by lifecrisis** [comment]
@joel1st, try updating the NERDTree and see if your problem is fixed.  I believe this will do it for you.
