### ISSUE TITLE
Hide square brackets around flag string?

### ISSUE THREAD

**Issue by eivindml** [scrooloose/nerdtree#815]
Hi,

is there a way, or is it possible to add an option to hide the square brackets around the flag string (e.g. used by the nerdtree-git-plugin)? I think that would look much cleaner. 

![Screenshot](https://user-images.githubusercontent.com/202450/37259534-cfaea464-2587-11e8-90cf-c358de301a3a.png)

Relevant code here: https://github.com/scrooloose/nerdtree/blob/509122df20e200b50e887c32cb7d92b19171a4ab/lib/nerdtree/flag_set.vim#L55

**Comment by kutsan** [comment]
```vim
augroup nerdtreeconcealbrackets
      autocmd!
      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=ALL
      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=ALL
      autocmd FileType nerdtree setlocal conceallevel=3
      autocmd FileType nerdtree setlocal concealcursor=nvic
augroup END
```

**Comment by eivindml** [comment]
Thank you for this. :) 

It did work, but it was a bit buggy. The "+" symbol was a too close. And I would prefer to have a space between the symbol and the title. Maybe to have the icons at the end of the title would be best, so the indentation of files/folders are always the same. Now it can be a bit visually confusing as they get indented differently depending on if they have a icon or not. 

Think I will stick with default settings for now. :) But I will check out the great bonus tips. 

<img width="1310" alt="screen shot 2018-03-13 at 12 53 09" src="https://user-images.githubusercontent.com/202450/37340203-a1fdc158-26bd-11e8-910f-9d7925e8f083.png">

For others seeing this, remember that default vim shipped with macOS doesn't have the conceal thing, so you need to get a newer `vim` from `homebrew` for instance. (I didn't know this at first)

**Comment by PhilRunninger** [comment]
Changing the `conceallevel` from 3 to 1 will introduce the space you're looking for. See `:h conceallevel`.

**Comment by eivindml** [comment]
thanks. :) Then this happened? 

<img width="1310" alt="screen shot 2018-03-13 at 13 14 24" src="https://user-images.githubusercontent.com/202450/37341082-800508a6-26c0-11e8-9c51-b15d38e8ad50.png">

**Comment by PhilRunninger** [comment]
Or even better than `conceallevel=1`,
```
augroup nerdtreeconcealbrackets
      autocmd!
      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=ALL cchar= 
      autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=ALL
      autocmd FileType nerdtree setlocal conceallevel=2
      autocmd FileType nerdtree setlocal concealcursor=nvic
augroup END
```
The `cchar= ` value is a space. `conceallevel=2` uses that explicitly defined space to replace the `]`, and it completely hides the `[` because no `cchar` is specified for that one.

The reason your concealed characters are visible is because your color scheme is not setting the `Conceal` highlight. You can set it yourself or find another color scheme that does. See https://github.com/pangloss/vim-javascript/issues/151 for a discussion about this issue.

**Comment by kutsan** [comment]
@eivindml

> It did work, but it was a bit buggy. The "+" symbol was a too close. And I would prefer to have a space between the symbol and the title.

You can tweak that by adding a space character after each icon for that plugin. I know I know, it's still hacky solution but that's what we have.

```vim
let g:NERDTreeIndicatorMapCustom = {
    \ "Modified"  : "✹ ",
    \ "Staged"    : "✚ ",
    \ "Untracked" : "✭ ",
    \ "Renamed"   : "➜ ",
    \ "Unmerged"  : "═ ",
    \ "Deleted"   : "✖ ",
    \ "Dirty"     : "✗ ",
    \ "Clean"     : "✔︎ ",
    \ 'Ignored'   : '☒ ',
    \ "Unknown"   : "? "
    \ }
```

> Maybe to have the icons at the end of the title would be best, so the indentation of files/folders are always the same.

Yes, I feel you. That's probably why I don't use that plugin. I think it would be better to get rid off all icon stuff and just use highlighting instead of icons; if it's modified, then highlight its foreground color as yellow like other IDEs does.

NERDTree itself is poorly written, so its plugins use some hacks to achieve that kind of functionality.

**Comment by PhilRunninger** [comment]
@eivindml If you are satisfied with these answers, please close the issue. Thanks!

**Comment by eivindml** [comment]
Thanks for the help. I also think just highlighting the status with colour would be best.

I use Atom on and off, and how they do it works really well. 

Hopefully someone takes up the challenge to create something like this. Will close this issue.

<img width="597" alt="screen shot 2018-03-16 at 10 52 55" src="https://user-images.githubusercontent.com/202450/37514459-43cd6190-2908-11e8-931f-4f92599c7864.png">

**Comment by kutsan** [comment]
Back then, I did something with my local [nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin) fork but it was buggy, not usable; and due to vim highlight mechanics, it was slow; we were creating a highlight element every single file node, which is insane when it comes to performance. I don't have any motivation to continue now.

I've been using vim for years and I'd like to say it's not really great experience (at least for me) when you start to make some integration plugins like git.

![image](https://user-images.githubusercontent.com/10108377/37515149-ef50cb4e-291a-11e8-94a9-8eea3d2e5c73.png)

**Comment by eivindml** [comment]
Yeah. I can see that. That looks really good though. :)

**Comment by aanari** [comment]
Since I am also using the syntax highlighting plugin, this did the trick for me:
```vimscript
augroup nerdtree
  autocmd!
  autocmd FileType nerdtree syntax clear NERDTreeFlags
  autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\]" contained conceal containedin=ALL
  autocmd FileType nerdtree syntax match hideBracketsInNerdTree "\[" contained conceal containedin=ALL
  autocmd FileType nerdtree setlocal conceallevel=3
  autocmd FileType nerdtree setlocal concealcursor=nvic
augroup END
```
