### ISSUE TITLE
CWD not changed when bookmark points to file even with NERDTreeChDirMode=2

### ISSUE THREAD

**Issue by minusf** [scrooloose/nerdtree#865]
### Environment

* Operating System: `macos high sierra 10.13.6 (17G65)`
* Vim version `:version`: `NVIM v0.3.1`
* NERDTree version `git rev-parse --short HEAD`: `d6032c8`
* NERDTree settings applied in your vimrc, if any:
    ```vim
    let NERDTreeCaseSensitiveSort=1
    let NERDTreeChDirMode=2
    let NERDTreeMinimalUI=1
    let NERDTreeMouseMode=2
    let NERDTreeQuitOnOpen=1
    let NERDTreeRespectWildIgnore=1
    let NERDTreeShowBookmarks=1
    let NERDTreeShowHidden=1
    let NERDTreeSortHiddenFirst=1
    let NERDTreeWinSize=38
    nnoremap <leader>G :NERDTreeFind<CR>
    nnoremap <leader>t :let NERDTreeQuitOnOpen=1<Bar>NERDTreeToggle<CR>
    nnoremap <leader>T :let NERDTreeQuitOnOpen=0<Bar>NERDTreeToggle<CR>
    ```

### Process

1. Create bookmark on ~/src/project/
2. Selecting the bookmark will change the `cwd` to ~/src/project/
3. Create bookmark on ~/src/project/Makefile
4. Selecting this bookmark will not change the `cwd` to ~/src/project/

**Comment by PhilRunninger** [comment]
This option is designed to work only when changing the root of NERDTree. Since opening a file doesn't change the root, it's not applicable here.

Opening a bookmark that points to a folder sets the NERDTree root, as does the `C` command on a folder node. Of course `:NERDTree <path>` will set the root as well. These are the only times this option comes into play.

Therefore, I'm going to close this issue.
