### ISSUE TITLE
Mouse click does not align with where cursor ends up

### ISSUE THREAD

**Issue by rmoe88** [scrooloose/nerdtree#942]
### Environment

* Operating System: Ubuntu (16.04 and 18.04)
* Vim version `:version`: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 05 2018 21:42:14)   
Included patches: 1-1766                                             
* NERDTree version `git rev-parse --short HEAD`: 72c3656

### Process

1. With an empty vimrc other than your pluggin loader of choice and nerdtree installed, launch vim
2. "set mouse=a"
3. ":NERDTreeToggle"
4. Notice that, when clicking on files and folders other than the root node, and not on the first few characters of the node names, the cursor does not align with where the mouse was clicked.  The cursor gets left a few characters to the left of where the mouse was clicked.  In other words, if I were to click on the non-root node "Workspace" on the character 's', the cursor would end up on the 'o' incorrectly.  I have went through the process of removing all external variables I could find (default bashrc, sparse vimrc, different terminals, different machines, etc).

### Possible Fix

I have found that 91e0f2253fbecefa7e14f095950341584877ef19 was the last commit that does not have this problem.  Commits after this seem to have about a 1 character offset, and at some point on in more recent commits the problem grows to be about a 3 characters offset.

Thank You.

**Comment by PhilRunninger** [comment]
This happens because NERDTree is using the `conceal` feature to hide a BELL character (`'^G'`) that is being used to find the filename. If you turn `:syntax off` you will see the `^G`, and the alignment will be as you expect it. This behavior is inherent in Vim, not specific to NERDTree.  If this is something you'd like to see changed, submit an issue in the vim project.
