### ISSUE TITLE
how to recover a file deleted in the vim nerdtree panel (ubuntu 16.04)

### ISSUE THREAD

**Issue by smilesun** [scrooloose/nerdtree#958]

**Comment by PhilRunninger** [comment]
It's impossible through NERDTree. By default, it uses Vim's `delete()` function, which has no undo capability. However, if there is a command or utility in Linux that will move a deleted file to a Trash can, callable from the command line, you can specify it in the variable `g:NERDTreeRemoveFileCmd`. There's a similar variable to hold the command for removing directories: `g:NERDTreeRemoveDirCmd`.

To get the file back, you would need to follow the instructions of that command or utility.

**Comment by thiswillbeyourgithub** [comment]
For those wondering, I was frustrated by the use of `delete()` instead of `trash` on my linux.

So in `fsmenu.vim` I commented the line containing : 
`            call currentNode.delete() 
`
and put this instead :
`
            call system("trash '" . currentNode.path.str() . "' &")
`

I also edited the 24th line from
`
call NERDTreeAddMenuItem({'text': '(d)elete the current node', 'shortcut': 'd', 'callback': 'NERDTreeDeleteNode'})
`
to

`
call NERDTreeAddMenuItem({'text': '(t)rash the current node', 'shortcut': 't', 'callback': 'NERDTreeDeleteNode'})
`
